name: Deploy via FTP

on:
  push:
    branches:
      - main
      
jobs:
  deploy:
    name: Deploy website every commit
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v4

      - name: Sync files
        uses: public_html
        with:
          server: ftp.github.paymundi.com.br
          username: githubpaymundico
          password: ${{ secrets.FTP_PASSWORD_SITE1 }}